<!-- POtential danger: don't use local variables as they can be overridden! -->
<?php $name = 'Whatever'; ?>
<h1>Market View</h1>
Welcome <?= $this->escapeHtml($this->name) ?>!
<br />
The current time is: <?= $this->datetime ?>
<br />
<?= $this->partial('market/partials/categories', ['categories' => $this->categories]) ?>
<?php /*
<ul>
<li>
<?= implode('</li><li>', $this->categories) ?>
</li>
</ul> 
<?= $this->htmlList($this->categories) ?>
*/ ?>
<?php var_dump($this->request); ?>

